apiVersion: v1
kind: Secret
metadata:
  name: db-secret-basic-auth
type: kubernetes.io/basic-auth
data:
  username: cm9vdA==
  password: cm9vdA==
#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  postgres-db: "postgres"
  postgres-port: "5432"
  postgres-host: "db-service"
  redis-host: "redis-service"