apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      name: result-deployment
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: kaos-result
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: postgres-db
                  name: config
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: postgres-host
                  name: config
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: postgres-port
                  name: config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-secret-basic-auth
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: db-secret-basic-auth
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80